-- ════════════════════════════════════════════════════════════════════════
--  Field tasks (C3) — engineers/admins assign a located task to a viewer;
--  the viewer sees it in field mode, navigates to it, and marks it done.
--  RUN THIS ONCE in the Supabase SQL editor.
-- ════════════════════════════════════════════════════════════════════════
create table if not exists public.field_tasks (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  lat         double precision not null,
  lng         double precision not null,
  assigned_to uuid references public.profiles(id),
  created_by  uuid references public.profiles(id) default auth.uid(),
  status      text not null default 'open',          -- open | done
  created_at  timestamptz default now(),
  done_at     timestamptz
);

alter table public.field_tasks enable row level security;

-- viewer sees tasks assigned to them; engineer/admin see all
drop policy if exists field_tasks_sel on public.field_tasks;
create policy field_tasks_sel on public.field_tasks for select to authenticated
  using (assigned_to = auth.uid()
         or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('engineer','admin')));

-- engineer/admin create tasks
drop policy if exists field_tasks_ins on public.field_tasks;
create policy field_tasks_ins on public.field_tasks for insert to authenticated
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('engineer','admin')));

-- the assignee can mark their task done; engineer/admin can update any
drop policy if exists field_tasks_upd on public.field_tasks;
create policy field_tasks_upd on public.field_tasks for update to authenticated
  using (assigned_to = auth.uid()
         or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('engineer','admin')));
